'''
Created on Jul 5, 2014

@author: Leon
'''

def addRightSideToList(l):
    '''
    doesn't work because order matters
    '''
    toAdd = []
    for item in l:
        if 'LT_' in item:
            toAdd.append(item.replace('LT_', 'RT_'))
    return l + toAdd

# to switch off an action,
# just add '-' or something so it won't run
build_actions = ['-place',
                 '-bind',
                 '-sec_motion_system',
                 '-primary_ctl_system_first',
                 '-primary_ctl_system_second',
                 '-load_weights',
                 'clean',
                 '-eyes',
                 '-eyeballs']

# this list of lists is passed to the UI context while placing placers
baseFilePath = r'C:\Users\Leon\Pictures\FRS\Images\human\\'
# direct placers ['label', '3-token-name', bindType, orientType]
# bindType - direct, indirect, independent, surface
# orientType - user, normalPrimary, normalSecondary, world
placerMappings = [['Center Brow', 'CT__brow', 0, 1],
                  ['Left Inner Brow', 'LT_in_brow', 0, 1],
                   ['Left Middle Brow', 'LT_mid_brow', 0, 1],
                   ['Left Outer Brow', 'LT_out_brow', 0, 1],
                   ['Left Inner Forehead', 'LT_in_forehead', 0, 1],
                   ['Left Outer Forehead', 'LT_out_forehead', 0, 1],
                   ['Left Temple', 'LT__temple', 0, 1],
                   ['Center Nose Bridge', 'CT__noseBridge', 0, 3],
                   ['Center Nose Tip', 'CT__noseTip', 0, 3],
                   ['Left Nostril', 'LT__nostril', 0, 3],
                   ['Center Philtrum', 'LT_in_philtrum', 0, 1],
                   ['Left Philtrum', 'LT__philtrum', 0, 1],
                   ['Left Inner Cheek', 'LT_in_cheek', 0, 2],
                   ['Left Upper Cheek', 'LT_up_cheek', 0, 2],
                   ['Left Squint', 'LT__squint', 0, 2],
                   ['Left Upper Crease', 'LT_up_crease', 0, 1],
                   ['Left Middle Crease', 'LT_mid_crease', 0, 1],
                   ['Left Lower Crease', 'LT_low_crease', 0, 1],
                   ['Left Middle Cheek', 'LT_mid_cheek', 0, 2],
                   ['Left Lower Cheek', 'LT_low_cheek', 0, 2],
                   ['Left Upper Jaw', 'LT_up_jaw', 0, 1],
                   ['Left Jaw Corner', 'LT_corner_jaw', 0, 1],
                   ['Left Lower Jaw', 'LT_low_jaw', 0, 1],
                   ['Left Chin', 'LT__chin', 0, 1],
                   ['Left Mid Chin', 'LT_mid_chin', 0, 1],
                   ['Center Chin', 'CT__chin', 0, 1],
                   ['Center Mid Chin', 'CT_mid_chin', 0, 1],
                   ['Center Neck', 'CT__neck', 0, 1],
                   ['Left Neck', 'LT__neck', 0, 1]]


# placers will be added after UI-placement is completed
# {moverName: [pLocName, pLocName, ...]}
independentMappings = {'CT__jaw': ['LT_up_jaw_pLoc'],
                    'CT__mouthMover': ['CT_upper_lip_pLoc', 'CT_lower_lip_pLoc'],
                    'CT__base': ['LT__neck_pLoc']}

# list of priCtls for first pass
# order is important
# those created earlier can be affected by those created later
# only need to specify LT and CT - RT is added in all_bnds_for_priCtls

bnds_for_priCtls = [u'LT_upper_eyelid_pLoc',
                    u'LT_lower_eyelid_pLoc',
                    u'LT_mid_brow_pLoc',
                    u'CT__noseBridge_pLoc',
                    u'CT__noseTip_pLoc',
                    u'LT__squint_pLoc',
                    u'LT_low_cheek_pLoc',
                    u'CT_upper_lip_pLoc',
                    u'CT_lower_lip_pLoc',
                    u'LT_upperSneer_lip_pLoc',
                    u'LT_lowerSneer_lip_pLoc',
                    u'LT_corner_lip_pLoc',
                    u'CT__mouthMover_pLoc',
                    u'CT__jaw_pLoc',
                    u'LT_inner_eyelid_pLoc',
                    u'LT_outer_eyelid_pLoc']

all_bnds_for_priCtls = addRightSideToList(bnds_for_priCtls)

# format to save priCtlMappings
# {priCtl: {bnd: weight,
#             bnd: weight,
#             bnd: weight}}

priCtlMappings = {u'CT__jaw_pri_ctrl': {u'CT__base_bnd': 0.5,
                       u'CT__chin_bnd': 1.0,
                       u'CT__jaw_bnd': 0.1,
                       u'CT__neck_bnd': 0.25,
                       u'CT_lower_lip_bnd': 1.0,
                       u'CT_mid_chin_bnd': 1.0,
                       u'CT_upper_lip_bnd': 0.01,
                       u'LT__chin_bnd': 0.9,
                       u'LT__neck_bnd': 0.25,
                       u'LT__philtrum_bnd': 0.1,
                       u'LT_corner_jaw_bnd': 0.25,
                       u'LT_corner_lip_bnd': 0.5,
                       u'LT_in_philtrum_bnd': 0.05,
                       u'LT_low_cheek_bnd': 0.1,
                       u'LT_low_crease_bnd': 0.1,
                       u'LT_low_jaw_bnd': 0.8,
                       u'LT_lowerPinch_lip_bnd': 0.8,
                       u'LT_lowerSide_lip_bnd': 0.95,
                       u'LT_lowerSneer_lip_bnd': 0.9,
                       u'LT_mid_cheek_bnd': 0.05,
                       u'LT_mid_chin_bnd': 0.9,
                       u'LT_mid_crease_bnd': 0.1,
                       u'LT_up_crease_bnd': 0.05,
                       u'LT_up_jaw_bnd': 0.05,
                       u'LT_upperPinch_lip_bnd': 0.2,
                       u'LT_upperSide_lip_bnd': 0.05,
                       u'LT_upperSneer_lip_bnd': 0.1,
                       u'RT__chin_bnd': 0.9,
                       u'RT__neck_bnd': 0.25,
                       u'RT__philtrum_bnd': 0.1,
                       u'RT_corner_jaw_bnd': 0.25,
                       u'RT_corner_lip_bnd': 0.5,
                       u'RT_in_philtrum_bnd': 0.05,
                       u'RT_low_cheek_bnd': 0.1,
                       u'RT_low_crease_bnd': 0.1,
                       u'RT_low_jaw_bnd': 0.8,
                       u'RT_lowerPinch_lip_bnd': 0.8,
                       u'RT_lowerSide_lip_bnd': 0.95,
                       u'RT_lowerSneer_lip_bnd': 0.9,
                       u'RT_mid_cheek_bnd': 0.05,
                       u'RT_mid_chin_bnd': 0.9,
                       u'RT_mid_crease_bnd': 0.1,
                       u'RT_up_crease_bnd': 0.05,
                       u'RT_up_jaw_bnd': 0.05,
                       u'RT_upperPinch_lip_bnd': 0.2,
                       u'RT_upperSide_lip_bnd': 0.05,
                       u'RT_upperSneer_lip_bnd': 0.1},
 u'CT__mouthMover_pri_ctrl': {u'CT__mouthMover_bnd': 1.0,
                              u'CT_lower_lip_bnd': 1.0,
                              u'CT_mid_chin_bnd': 0.2,
                              u'CT_upper_lip_bnd': 1.0,
                              u'LT__philtrum_bnd': 0.2,
                              u'LT_corner_lip_bnd': 1.0,
                              u'LT_in_philtrum_bnd': 0.2,
                              u'LT_low_crease_bnd': 0.2,
                              u'LT_lowerPinch_lip_bnd': 1.0,
                              u'LT_lowerSide_lip_bnd': 1.0,
                              u'LT_lowerSneer_lip_bnd': 1.0,
                              u'LT_mid_chin_bnd': 0.2,
                              u'LT_mid_crease_bnd': 0.2,
                              u'LT_up_crease_bnd': 0.1,
                              u'LT_upperPinch_lip_bnd': 1.0,
                              u'LT_upperSide_lip_bnd': 1.0,
                              u'LT_upperSneer_lip_bnd': 1.0,
                              u'RT__philtrum_bnd': 0.2,
                              u'RT_corner_lip_bnd': 1.0,
                              u'RT_in_philtrum_bnd': 0.2,
                              u'RT_low_crease_bnd': 0.2,
                              u'RT_lowerPinch_lip_bnd': 1.0,
                              u'RT_lowerSide_lip_bnd': 1.0,
                              u'RT_lowerSneer_lip_bnd': 1.0,
                              u'RT_mid_chin_bnd': 0.2,
                              u'RT_mid_crease_bnd': 0.2,
                              u'RT_up_crease_bnd': 0.1,
                              u'RT_upperPinch_lip_bnd': 1.0,
                              u'RT_upperSide_lip_bnd': 1.0,
                              u'RT_upperSneer_lip_bnd': 1.0},
 u'CT__noseBridge_pri_ctrl': {u'CT__noseBridge_bnd': 1.0,
                              u'CT__noseTip_bnd': 1.0,
                              u'LT__nostril_bnd': 1.0,
                              u'LT__philtrum_bnd': 0.15,
                              u'LT_in_philtrum_bnd': 0.15,
                              u'LT_up_crease_bnd': 0.15,
                              u'RT__nostril_bnd': 1.0,
                              u'RT__philtrum_bnd': 0.15,
                              u'RT_in_philtrum_bnd': 0.15,
                              u'RT_up_crease_bnd': 0.15},
 u'CT__noseTip_pri_ctrl': {u'CT__noseTip_bnd': 1.0,
                           u'LT__nostril_bnd': 1.0,
                           u'LT__philtrum_bnd': 0.15,
                           u'LT_in_philtrum_bnd': 0.15,
                           u'LT_up_crease_bnd': 0.15,
                           u'RT__nostril_bnd': 1.0,
                           u'RT__philtrum_bnd': 0.15,
                           u'RT_in_philtrum_bnd': 0.15,
                           u'RT_up_crease_bnd': 0.15},
 u'CT_lower_lip_pri_ctrl': {u'CT_lower_lip_bnd': 1.0,
                            u'LT_lowerPinch_lip_bnd': 0.1111,
                            u'LT_lowerSide_lip_bnd': 0.6666,
                            u'LT_lowerSneer_lip_bnd': 0.3333,
                            u'RT_lowerPinch_lip_bnd': 0.1111,
                            u'RT_lowerSide_lip_bnd': 0.6666,
                            u'RT_lowerSneer_lip_bnd': 0.3333},
 u'CT_upper_lip_pri_ctrl': {u'CT__jaw_bnd': 1.0,
                            u'CT_upper_lip_bnd': 1.0,
                            u'LT_upperPinch_lip_bnd': 0.1111,
                            u'LT_upperSide_lip_bnd': 0.6666,
                            u'LT_upperSneer_lip_bnd': 0.3333,
                            u'RT_upperPinch_lip_bnd': 0.1111,
                            u'RT_upperSide_lip_bnd': 0.6666,
                            u'RT_upperSneer_lip_bnd': 0.3333},
 u'LT__squint_pri_ctrl': {u'LT__squint_bnd': 1.0,
                          u'LT_in_cheek_bnd': 1.0,
                          u'LT_low_cheek_bnd': 0.1,
                          u'LT_low_crease_bnd': 0.1,
                          u'LT_mid_cheek_bnd': 0.5,
                          u'LT_mid_crease_bnd': 0.2,
                          u'LT_up_cheek_bnd': 1.0,
                          u'LT_up_crease_bnd': 0.2},
 u'LT_corner_lip_pri_ctrl': {u'CT__jaw_bnd': 0.3,
                             u'CT_lower_lip_bnd': 0.05,
                             u'CT_mid_chin_bnd': 0.05,
                             u'CT_upper_lip_bnd': 0.05,
                             u'LT__philtrum_bnd': 0.1,
                             u'LT_corner_lip_bnd': 1.0,
                             u'LT_in_philtrum_bnd': 0.05,
                             u'LT_low_cheek_bnd': 0.05,
                             u'LT_low_crease_bnd': 0.5,
                             u'LT_lowerPinch_lip_bnd': 0.85,
                             u'LT_lowerSide_lip_bnd': 0.3,
                             u'LT_lowerSneer_lip_bnd': 0.6,
                             u'LT_mid_cheek_bnd': 0.05,
                             u'LT_mid_chin_bnd': 0.3,
                             u'LT_mid_crease_bnd': 0.3,
                             u'LT_up_crease_bnd': 0.1,
                             u'LT_upperPinch_lip_bnd': 0.85,
                             u'LT_upperSide_lip_bnd': 0.3,
                             u'LT_upperSneer_lip_bnd': 0.6},
 u'LT_inner_eyelid_pri_ctrl': {u'LT_innerLower_eyelid_bnd': 1.0,
                               u'LT_innerUpper_eyelid_bnd': 1.0,
                               u'LT_inner_eyelid_bnd': 1.0},
 u'LT_low_cheek_pri_ctrl': {u'LT__squint_bnd': 0.1,
                            u'LT_low_cheek_bnd': 1.0,
                            u'LT_low_crease_bnd': 0.5,
                            u'LT_mid_cheek_bnd': 0.5,
                            u'LT_mid_crease_bnd': 0.25,
                            u'LT_up_cheek_bnd': 0.1,
                            u'LT_up_jaw_bnd': 0.1},
 u'LT_lowerSneer_lip_pri_ctrl': {u'CT_lower_lip_bnd': 0.25,
                                 u'LT_lowerPinch_lip_bnd': 0.1111,
                                 u'LT_lowerSide_lip_bnd': 0.5,
                                 u'LT_lowerSneer_lip_bnd': 1.0},
 u'LT_lower_eyelid_pri_ctrl': {u'LT_innerLower_eyelid_bnd': 1.0,
                               u'LT_inner_eyelid_bnd': 1.0,
                               u'LT_lower_eyelid_bnd': 1.0,
                               u'LT_outerLower_eyelid_bnd': 1.0,
                               u'LT_outer_eyelid_bnd': 1.0},
 u'LT_mid_brow_pri_ctrl': {u'CT__brow_bnd': 0.5,
                           u'LT_in_brow_bnd': 1.0,
                           u'LT_in_forehead_bnd': 0.25,
                           u'LT_mid_brow_bnd': 1.0,
                           u'LT_out_brow_bnd': 1.0,
                           u'LT_out_forehead_bnd': 0.25},
 u'LT_outer_eyelid_pri_ctrl': {u'LT_outerLower_eyelid_bnd': 1.0,
                               u'LT_outerUpper_eyelid_bnd': 1.0,
                               u'LT_outer_eyelid_bnd': 1.0},
 u'LT_upperSneer_lip_pri_ctrl': {u'CT_upper_lip_bnd': 0.25,
                                 u'LT_upperPinch_lip_bnd': 0.3333,
                                 u'LT_upperSide_lip_bnd': 0.5,
                                 u'LT_upperSneer_lip_bnd': 1.0},
 u'LT_upper_eyelid_pri_ctrl': {u'LT_innerUpper_eyelid_bnd': 1.0,
                               u'LT_inner_eyelid_bnd': 1.0,
                               u'LT_outerUpper_eyelid_bnd': 1.0,
                               u'LT_outer_eyelid_bnd': 1.0,
                               u'LT_upper_eyelid_bnd': 1.0},
 u'RT__squint_pri_ctrl': {u'RT__squint_bnd': 1.0,
                          u'RT_in_cheek_bnd': 1.0,
                          u'RT_low_cheek_bnd': 0.1,
                          u'RT_low_crease_bnd': 0.1,
                          u'RT_mid_cheek_bnd': 0.5,
                          u'RT_mid_crease_bnd': 0.2,
                          u'RT_up_cheek_bnd': 1.0,
                          u'RT_up_crease_bnd': 0.2},
 u'RT_corner_lip_pri_ctrl': {u'CT__jaw_bnd': 0.3,
                             u'CT_lower_lip_bnd': 0.05,
                             u'CT_mid_chin_bnd': 0.05,
                             u'CT_upper_lip_bnd': 0.05,
                             u'RT__philtrum_bnd': 0.1,
                             u'RT_corner_lip_bnd': 1.0,
                             u'RT_in_philtrum_bnd': 0.05,
                             u'RT_low_cheek_bnd': 0.05,
                             u'RT_low_crease_bnd': 0.5,
                             u'RT_lowerPinch_lip_bnd': 0.85,
                             u'RT_lowerSide_lip_bnd': 0.3,
                             u'RT_lowerSneer_lip_bnd': 0.6,
                             u'RT_mid_cheek_bnd': 0.05,
                             u'RT_mid_chin_bnd': 0.3,
                             u'RT_mid_crease_bnd': 0.3,
                             u'RT_up_crease_bnd': 0.1,
                             u'RT_upperPinch_lip_bnd': 0.85,
                             u'RT_upperSide_lip_bnd': 0.3,
                             u'RT_upperSneer_lip_bnd': 0.6},
 u'RT_inner_eyelid_pri_ctrl': {u'RT_innerLower_eyelid_bnd': 1.0,
                               u'RT_innerUpper_eyelid_bnd': 1.0,
                               u'RT_inner_eyelid_bnd': 1.0},
 u'RT_low_cheek_pri_ctrl': {u'RT__squint_bnd': 0.1,
                            u'RT_low_cheek_bnd': 1.0,
                            u'RT_low_crease_bnd': 0.5,
                            u'RT_mid_cheek_bnd': 0.5,
                            u'RT_mid_crease_bnd': 0.25,
                            u'RT_up_cheek_bnd': 0.1,
                            u'RT_up_jaw_bnd': 0.1},
 u'RT_lowerSneer_lip_pri_ctrl': {u'CT_lower_lip_bnd': 0.25,
                                 u'RT_lowerPinch_lip_bnd': 0.1111,
                                 u'RT_lowerSide_lip_bnd': 0.5,
                                 u'RT_lowerSneer_lip_bnd': 1.0},
 u'RT_lower_eyelid_pri_ctrl': {u'RT_innerLower_eyelid_bnd': 1.0,
                               u'RT_inner_eyelid_bnd': 1.0,
                               u'RT_lower_eyelid_bnd': 1.0,
                               u'RT_outerLower_eyelid_bnd': 1.0,
                               u'RT_outer_eyelid_bnd': 1.0},
 u'RT_mid_brow_pri_ctrl': {u'CT__brow_bnd': 0.5,
                           u'RT_in_brow_bnd': 1.0,
                           u'RT_in_forehead_bnd': 0.25,
                           u'RT_mid_brow_bnd': 1.0,
                           u'RT_out_brow_bnd': 1.0,
                           u'RT_out_forehead_bnd': 0.25},
 u'RT_outer_eyelid_pri_ctrl': {u'RT_outerLower_eyelid_bnd': 1.0,
                               u'RT_outerUpper_eyelid_bnd': 1.0,
                               u'RT_outer_eyelid_bnd': 1.0},
 u'RT_upperSneer_lip_pri_ctrl': {u'CT_upper_lip_bnd': 0.25,
                                 u'RT_upperPinch_lip_bnd': 0.3333,
                                 u'RT_upperSide_lip_bnd': 0.5,
                                 u'RT_upperSneer_lip_bnd': 1.0},
 u'RT_upper_eyelid_pri_ctrl': {u'RT_innerUpper_eyelid_bnd': 1.0,
                               u'RT_inner_eyelid_bnd': 1.0,
                               u'RT_outerUpper_eyelid_bnd': 1.0,
                               u'RT_outer_eyelid_bnd': 1.0,
                               u'RT_upper_eyelid_bnd': 1.0}} 

