'''
Created on Jul 5, 2014

@author: Leon
'''

def addRightSideToList(l):
    '''
    doesn't work because order matters
    '''
    toAdd = []
    for item in l:
        if 'LT_' in item:
            toAdd.append(item.replace('LT_', 'RT_'))
    return l + toAdd

# to switch off an action,
# just add '-' or something so it won't run
build_actions = ['-bind',
                 '-sec_motion_system',
                 '-primary_ctl_system_first',
                 'primary_ctl_system_second',
                 '-load_weights',
                 '-clean',
                 '-eyes',
                 '-eyeballs']

# list of priCtls for first pass
# order is important
# those created earlier can be affected by those created later
# only need to specify LT and CT - RT is added in all_bnds_for_priCtls

bnds_for_priCtls = [u'LT_mid_brow_pLoc',
                    u'LT_eyelid_upper_pLoc',
                    u'LT_eyelid_lower_pLoc',
                    u'CT_noseMover_pLoc',
                    u'CT_noseTip_pLoc',
                    u'CT_jaw_pLoc',
                    u'LT_cheek_pLoc',
                    u'LT_corner_lip_pLoc',
                    u'CT_mouthMover_pLoc',
                    u'CT_upper_lip_pLoc',
                    u'CT_lower_lip_pLoc',
                    u'LT_upper_sneer_lip_pLoc',
                    u'LT_lower_sneer_lip_pLoc']

all_bnds_for_priCtls = addRightSideToList(bnds_for_priCtls)

# format to save priCtlMappings
# {priCtl: {bnd: weight,
#             bnd: weight,
#             bnd: weight}}

priCtlMappings = {u'CT_jaw_pri_ctrl': {u'CT_chin_bnd': 1.0,
                             u'CT_jaw_bnd': 1.0,
                             u'CT_lower_lip_bnd': 1.0,
                             u'CT_mid_chin_bnd': 1.0,
                             u'CT_neck_bnd': 1.0,
                             u'CT_philtrum_bnd': 0.01,
                             u'CT_upper_lip_bnd': 0.01,
                             u'LT_cheek_bnd': 0.5,
                             u'LT_chin_bnd': 1.0,
                             u'LT_corner_jaw_bnd': 0.25,
                             u'LT_corner_lip_bnd': 0.5,
                             u'LT_in_philtrum_bnd': 0.02,
                             u'LT_low_crease_bnd': 0.5,
                             u'LT_low_jaw_bnd': 1.0,
                             u'LT_lower_pinch_lip_bnd': 0.75,
                             u'LT_lower_side_lip_bnd': 0.95,
                             u'LT_lower_sneer_lip_bnd': 0.85,
                             u'LT_mid_chin_bnd': 1.0,
                             u'LT_mid_crease_bnd': 0.25,
                             u'LT_neck_bnd': 0.6,
                             u'LT_philtrum_bnd': 0.05,
                             u'LT_sneer_bnd': 0.05,
                             u'LT_up_crease_bnd': 0.05,
                             u'LT_up_jaw_bnd': 0.05,
                             u'LT_upper_pinch_lip_bnd': 0.25,
                             u'LT_upper_side_lip_bnd': 0.05,
                             u'LT_upper_sneer_lip_bnd': 0.15,
                             u'RT_cheek_bnd': 0.5,
                             u'RT_chin_bnd': 1.0,
                             u'RT_corner_jaw_bnd': 0.25,
                             u'RT_corner_lip_bnd': 0.5,
                             u'RT_in_philtrum_bnd': 0.02,
                             u'RT_low_crease_bnd': 0.5,
                             u'RT_low_jaw_bnd': 1.0,
                             u'RT_lower_pinch_lip_bnd': 0.75,
                             u'RT_lower_side_lip_bnd': 0.95,
                             u'RT_lower_sneer_lip_bnd': 0.85,
                             u'RT_mid_chin_bnd': 1.0,
                             u'RT_mid_crease_bnd': 0.25,
                             u'RT_neck_bnd': 0.6,
                             u'RT_philtrum_bnd': 0.05,
                             u'RT_sneer_bnd': 0.05,
                             u'RT_up_crease_bnd': 0.05,
                             u'RT_up_jaw_bnd': 0.05,
                             u'RT_upper_pinch_lip_bnd': 0.25,
                             u'RT_upper_side_lip_bnd': 0.05,
                             u'RT_upper_sneer_lip_bnd': 0.15},
 u'CT_lower_lip_pri_ctrl': {u'CT_lower_lip_bnd': 1.0,
                            u'LT_lower_pinch_lip_bnd': 0.25,
                            u'LT_lower_side_lip_bnd': 0.75,
                            u'LT_lower_sneer_lip_bnd': 0.5,
                            u'RT_lower_pinch_lip_bnd': 0.25,
                            u'RT_lower_side_lip_bnd': 0.75,
                            u'RT_lower_sneer_lip_bnd': 0.5},
 u'CT_mouthMover_pri_ctrl': {u'CT_lower_lip_bnd': 1.0,
                                    u'CT_mid_chin_bnd': 0.5,
                                    u'CT_mouthMover_bnd': 1.0,
                                    u'CT_philtrum_bnd': 0.1,
                                    u'CT_upper_lip_bnd': 1.0,
                                    u'LT_corner_lip_bnd': 1.0,
                                    u'LT_in_philtrum_bnd': 0.1,
                                    u'LT_low_crease_bnd': 0.5,
                                    u'LT_lower_pinch_lip_bnd': 1.0,
                                    u'LT_lower_side_lip_bnd': 1.0,
                                    u'LT_lower_sneer_lip_bnd': 1.0,
                                    u'LT_mid_chin_bnd': 0.5,
                                    u'LT_mid_crease_bnd': 0.5,
                                    u'LT_philtrum_bnd': 0.1,
                                    u'LT_sneer_bnd': 0.5,
                                    u'LT_up_crease_bnd': 0.5,
                                    u'LT_upper_pinch_lip_bnd': 1.0,
                                    u'LT_upper_side_lip_bnd': 1.0,
                                    u'LT_upper_sneer_lip_bnd': 1.0,
                                    u'RT_corner_lip_bnd': 1.0,
                                    u'RT_in_philtrum_bnd': 0.1,
                                    u'RT_low_crease_bnd': 0.5,
                                    u'RT_lower_pinch_lip_bnd': 1.0,
                                    u'RT_lower_side_lip_bnd': 1.0,
                                    u'RT_lower_sneer_lip_bnd': 1.0,
                                    u'RT_mid_chin_bnd': 0.5,
                                    u'RT_mid_crease_bnd': 0.5,
                                    u'RT_philtrum_bnd': 0.1,
                                    u'RT_sneer_bnd': 0.5,
                                    u'RT_up_crease_bnd': 0.5,
                                    u'RT_upper_pinch_lip_bnd': 1.0,
                                    u'RT_upper_side_lip_bnd': 1.0,
                                    u'RT_upper_sneer_lip_bnd': 1.0},
 u'CT_noseMover_pri_ctrl': {u'CT_noseMover_bnd': 1.0,
                                   u'CT_noseTip_bnd': 1.0,
                                   u'CT_philtrum_bnd': 1.0,
                                   u'LT_in_philtrum_bnd': 1.0,
                                   u'LT_nostril_bnd': 1.0,
                                   u'LT_philtrum_bnd': 1.0,
                                   u'LT_up_crease_bnd': 1.0,
                                   u'RT_in_philtrum_bnd': 1.0,
                                   u'RT_nostril_bnd': 1.0,
                                   u'RT_philtrum_bnd': 1.0,
                                   u'RT_up_crease_bnd': 1.0},
 u'CT_noseTip_pri_ctrl': {u'CT_noseTip_bnd': 1.0,
                                 u'CT_philtrum_bnd': 0.1,
                                 u'LT_in_philtrum_bnd': 0.1,
                                 u'LT_nostril_bnd': 1.0,
                                 u'LT_philtrum_bnd': 0.1,
                                 u'LT_up_crease_bnd': 0.1,
                                 u'RT_in_philtrum_bnd': 0.1,
                                 u'RT_nostril_bnd': 1.0,
                                 u'RT_philtrum_bnd': 0.1,
                                 u'RT_up_crease_bnd': 0.1},
 u'CT_upper_lip_pri_ctrl': {u'CT_upper_lip_bnd': 1.0,
                            u'LT_upper_pinch_lip_bnd': 0.25,
                            u'LT_upper_side_lip_bnd': 0.75,
                            u'LT_upper_sneer_lip_bnd': 0.5,
                            u'RT_upper_pinch_lip_bnd': 0.25,
                            u'RT_upper_side_lip_bnd': 0.75,
                            u'RT_upper_sneer_lip_bnd': 0.5},
 u'LT_cheek_pri_ctrl': {u'LT_cheek_bnd': 1.0,
                               u'LT_corner_jaw_bnd': 0.1,
                               u'LT_corner_lip_bnd': 0.1,
                               u'LT_in_cheek_bnd': 0.1,
                               u'LT_low_crease_bnd': 0.65,
                               u'LT_low_jaw_bnd': 0.1,
                               u'LT_lower_pinch_lip_bnd': 0.05,
                               u'LT_mid_crease_bnd': 0.65,
                               u'LT_out_cheek_bnd': 0.1,
                               u'LT_sneer_bnd': 0.1,
                               u'LT_squint_bnd': 0.1,
                               u'LT_up_cheek_bnd': 0.1,
                               u'LT_up_crease_bnd': 0.1,
                               u'LT_up_jaw_bnd': 0.65,
                               u'LT_upper_pinch_lip_bnd': 0.05},
 u'LT_corner_lip_pri_ctrl': {u'CT_lower_lip_bnd': 0.1,
                             u'CT_mid_chin_bnd': 0.05,
                             u'CT_philtrum_bnd': 0.02,
                             u'CT_upper_lip_bnd': 0.1,
                             u'LT_corner_lip_bnd': 1.0,
                             u'LT_in_philtrum_bnd': 0.05,
                             u'LT_low_crease_bnd': 0.4,
                             u'LT_lower_pinch_lip_bnd': 0.75,
                             u'LT_lower_side_lip_bnd': 0.18,
                             u'LT_lower_sneer_lip_bnd': 0.45,
                             u'LT_mid_chin_bnd': 0.2,
                             u'LT_mid_crease_bnd': 0.2,
                             u'LT_philtrum_bnd': 0.2,
                             u'LT_sneer_bnd': 0.5,
                             u'LT_up_crease_bnd': 0.05,
                             u'LT_upper_pinch_lip_bnd': 0.75,
                             u'LT_upper_side_lip_bnd': 0.18,
                             u'LT_upper_sneer_lip_bnd': 0.45},
 u'LT_eyelid_lower_pri_ctrl': {u'LT_eyelid_inner_bnd': 1.0,
                               u'LT_eyelid_inner_lower_bnd': 1.0,
                               u'LT_eyelid_lower_bnd': 1.0,
                               u'LT_eyelid_outer_bnd': 1.0,
                               u'LT_eyelid_outer_lower_bnd': 1.0},
 u'LT_eyelid_upper_pri_ctrl': {u'LT_eyelid_inner_bnd': 1.0,
                               u'LT_eyelid_inner_upper_bnd': 1.0,
                               u'LT_eyelid_outer_bnd': 1.0,
                               u'LT_eyelid_outer_upper_bnd': 1.0,
                               u'LT_eyelid_upper_bnd': 1.0},
 u'LT_lower_sneer_lip_pri': {u'CT_lower_lip_bnd': 0.25,
                             u'LT_lower_pinch_lip_bnd': 0.5,
                             u'LT_lower_side_lip_bnd': 0.5,
                             u'LT_lower_sneer_lip_bnd': 1.0},
 u'LT_mid_brow_pri_ctrl': {u'CT_brow_bnd': 0.5,
                           u'LT_in_brow_bnd': 1.0,
                           u'LT_in_forehead_bnd': 0.1,
                           u'LT_in_low_forehead_bnd': 0.5,
                           u'LT_mid_brow_bnd': 1.0,
                           u'LT_out_brow_bnd': 1.0,
                           u'LT_out_forehead_bnd': 0.1,
                           u'LT_out_low_forehead_bnd': 0.5,
                           u'LT_temple_bnd': 0.1},
 u'LT_upper_sneer_lip_pri': {u'CT_upper_lip_bnd': 0.25,
                             u'LT_upper_pinch_lip_bnd': 0.5,
                             u'LT_upper_side_lip_bnd': 0.5,
                             u'LT_upper_sneer_lip_bnd': 1.0},
 u'RT_cheek_pri_ctrl': {u'RT_cheek_bnd': 1.0,
                               u'RT_corner_jaw_bnd': 0.1,
                               u'RT_corner_lip_bnd': 0.1,
                               u'RT_in_cheek_bnd': 0.1,
                               u'RT_low_crease_bnd': 0.65,
                               u'RT_low_jaw_bnd': 0.1,
                               u'RT_lower_pinch_lip_bnd': 0.05,
                               u'RT_mid_crease_bnd': 0.65,
                               u'RT_out_cheek_bnd': 0.1,
                               u'RT_sneer_bnd': 0.1,
                               u'RT_squint_bnd': 0.1,
                               u'RT_up_cheek_bnd': 0.1,
                               u'RT_up_crease_bnd': 0.1,
                               u'RT_up_jaw_bnd': 0.65,
                               u'RT_upper_pinch_lip_bnd': 0.05},
 u'RT_corner_lip_pri_ctrl': {u'CT_lower_lip_bnd': 0.1,
                             u'CT_mid_chin_bnd': 0.05,
                             u'CT_philtrum_bnd': 0.02,
                             u'CT_upper_lip_bnd': 0.1,
                             u'RT_corner_lip_bnd': 1.0,
                             u'RT_in_philtrum_bnd': 0.05,
                             u'RT_low_crease_bnd': 0.4,
                             u'RT_lower_pinch_lip_bnd': 0.75,
                             u'RT_lower_side_lip_bnd': 0.18,
                             u'RT_lower_sneer_lip_bnd': 0.45,
                             u'RT_mid_chin_bnd': 0.2,
                             u'RT_mid_crease_bnd': 0.2,
                             u'RT_philtrum_bnd': 0.2,
                             u'RT_sneer_bnd': 0.5,
                             u'RT_up_crease_bnd': 0.05,
                             u'RT_upper_pinch_lip_bnd': 0.75,
                             u'RT_upper_side_lip_bnd': 0.18,
                             u'RT_upper_sneer_lip_bnd': 0.45},
 u'RT_eyelid_lower_pri_ctrl': {u'RT_eyelid_inner_bnd': 1.0,
                               u'RT_eyelid_inner_lower_bnd': 1.0,
                               u'RT_eyelid_lower_bnd': 1.0,
                               u'RT_eyelid_outer_bnd': 1.0,
                               u'RT_eyelid_outer_lower_bnd': 1.0},
 u'RT_eyelid_upper_pri_ctrl': {u'RT_eyelid_inner_bnd': 1.0,
                               u'RT_eyelid_inner_upper_bnd': 1.0,
                               u'RT_eyelid_outer_bnd': 1.0,
                               u'RT_eyelid_outer_upper_bnd': 1.0,
                               u'RT_eyelid_upper_bnd': 1.0},
 u'RT_lower_sneer_lip_pri': {u'CT_lower_lip_bnd': 0.25,
                             u'RT_lower_pinch_lip_bnd': 0.5,
                             u'RT_lower_side_lip_bnd': 0.5,
                             u'RT_lower_sneer_lip_bnd': 1.0},
 u'RT_mid_brow_pri_ctrl': {u'CT_brow_bnd': 0.5,
                           u'RT_in_brow_bnd': 1.0,
                           u'RT_in_forehead_bnd': 0.1,
                           u'RT_in_low_forehead_bnd': 0.5,
                           u'RT_mid_brow_bnd': 1.0,
                           u'RT_out_brow_bnd': 1.0,
                           u'RT_out_forehead_bnd': 0.1,
                           u'RT_out_low_forehead_bnd': 0.5,
                           u'RT_temple_bnd': 0.1},
 u'RT_upper_sneer_lip_pri': {u'CT_upper_lip_bnd': 0.25,
                             u'RT_upper_pinch_lip_bnd': 0.5,
                             u'RT_upper_side_lip_bnd': 0.5,
                             u'RT_upper_sneer_lip_bnd': 1.0}} # 

