def addRightSideToList(l):
    '''
    doesn't work because order matters
    '''
    toAdd = []
    for item in l:
        if 'LT_' in item:
            toAdd.append(item.replace('LT_', 'RT_'))
    return l + toAdd

# to switch off an action,
# just add '-' or something so it won't run
build_actions = ['-bind',
                 '-sec_motion_system',
                 '-primary_ctl_system_first',
                 'primary_ctl_system_second',
                 '-load_weights',
                 '-clean',
                 '-surface_constraint',
                 '-eyes',
                 '-eyeballs']

# bnds to attach to surface
slidingBnds = [u'LT_upperPinch_outCrease_bnd',
                u'LT_corner_outCrease_bnd',
                u'LT_lowerCorner_outCrease_bnd',
                u'LT_corner_cheek_bnd',
                u'LT_outerB_cheekB_bnd',
                u'LT_lowerSneer_outCrease_bnd',
                u'CT_lower_midCrease_bnd',
                u'CT_lower_cheek_bnd',
                u'LT_lowerSide_outCrease_bnd',
                u'LT_lowerPinch_lip_bnd',
                u'LT_upperSide_lip_bnd',
                u'CT_lower_lip_bnd',
                u'LT_lowerSneer_lip_bnd',
                u'LT_corner_lip_bnd',
                u'LT_lowerSide_lip_bnd',
                u'CT_upper_lip_bnd',
                u'LT_upperPinch_lip_bnd',
                u'LT_upperSneer_lip_bnd',
                u'LT_lowerOuter_eyeSocket_bnd',
                u'LT_lowerPinch_cheek_bnd',
                u'LT_lowerInner_eyeSocket_bnd',
                u'LT_lower_eyeSocket_bnd',
                u'LT_upperSide_inCrease_bnd',
                u'CT_lower_inCrease_bnd',
                u'LT_lowerSide_inCrease_bnd',
                u'CT_upper_cheek_bnd',
                u'CT_upper_inCrease_bnd',
                u'LT_lowerPinch_inCrease_bnd',
                u'LT_upperPinch_inCrease_bnd',
                u'LT_lowerSide_midCrease_bnd',
                u'LT_lowerSide_cheek_bnd',
                u'LT_upperCorner_cheek_bnd',
                u'LT_lowerCorner_cheek_bnd',
                u'LT_outerB_cheekA_bnd',
                u'LT_outerB_cheekC_bnd',
                u'LT_lowerPinch_midCrease_bnd',
                u'LT_lowerSneer_cheek_bnd',
                u'LT_lowerPinch_outCrease_bnd',
                u'LT_outerB_cheekD_bnd',
                u'CT_upper_midCrease_bnd',
                u'CT_upper_outCrease_bnd',
                u'LT_upperSide_midCrease_bnd',
                u'LT_upperSide_outCrease_bnd',
                u'LT_upperSneer_inCrease_bnd',
                u'LT_upperSneer_midCrease_bnd',
                u'LT_upperSneer_outCrease_bnd',
                u'LT_upperPinch_midCrease_bnd',
                u'CT_lower_outCrease_bnd',
                u'LT_lowerSneer_inCrease_bnd',
                u'LT_lowerSneer_midCrease_bnd',
                u'LT_upperCorner_lip_bnd',
                u'LT_lowerCorner_lip_bnd',
                u'LT_upperCorner_inCrease_bnd',
                u'LT_upperCorner_midCrease_bnd',
                u'LT_upperCorner_outCrease_bnd',
                u'LT_corner_inCrease_bnd',
                u'LT_corner_midCrease_bnd',
                u'LT_lowerCorner_inCrease_bnd',
                u'LT_lowerCorner_midCrease_bnd',
                u'LT_mid_browA_bnd',
                u'LT_out_browA_bnd',
                u'LT_outerB_temple_bnd',
                u'LT_outerB_squint_bnd',
                u'CT_mid_forehead_bnd',
                u'LT_outerA_temple_bnd',
                u'LT_in_browA_bnd',
                u'LT_upper_eyeSocket_bnd',
                u'LT_upperInner_eyeSocket_bnd',
                u'LT_upperOuter_eyeSocket_bnd',
                u'LT_outer_eyeSocket_bnd',
                u'LT_inner_eyeSocket_bnd',
                u'CT_mid_temple_bnd',
                u'CT_mid_squint_bnd',
                u'LT_outerA_squint_bnd',
                u'LT_side_forehead_bnd',
                u'LT_outerA_forehead_bnd',
                u'LT_outerB_forehead_bnd',
                u'LT_outerC_cheekB_bnd',
                u'LT_outerC_cheekA_bnd',
                u'LT_outerC_cheekC_bnd',
                u'LT_outerC_cheekD_bnd',
                u'LT_outerC_temple_bnd',
                u'LT_outerC_squint_bnd',
                u'LT_outerC_forehead_bnd',
                u'RT_upperPinch_outCrease_bnd',
                u'RT_corner_outCrease_bnd',
                u'RT_lowerCorner_outCrease_bnd',
                u'RT_corner_cheek_bnd',
                u'RT_outerB_cheekB_bnd',
                u'RT_lowerSneer_outCrease_bnd',
                u'RT_lowerSide_outCrease_bnd',
                u'RT_lowerPinch_lip_bnd',
                u'RT_upperSide_lip_bnd',
                u'RT_lowerSneer_lip_bnd',
                u'RT_corner_lip_bnd',
                u'RT_lowerSide_lip_bnd',
                u'RT_upperPinch_lip_bnd',
                u'RT_upperSneer_lip_bnd',
                u'RT_lowerOuter_eyeSocket_bnd',
                u'RT_lowerPinch_cheek_bnd',
                u'RT_lowerInner_eyeSocket_bnd',
                u'RT_lower_eyeSocket_bnd',
                u'RT_upperSide_inCrease_bnd',
                u'RT_lowerSide_inCrease_bnd',
                u'RT_lowerPinch_inCrease_bnd',
                u'RT_upperPinch_inCrease_bnd',
                u'RT_lowerSide_midCrease_bnd',
                u'RT_lowerSide_cheek_bnd',
                u'RT_upperCorner_cheek_bnd',
                u'RT_lowerCorner_cheek_bnd',
                u'RT_outerB_cheekA_bnd',
                u'RT_outerB_cheekC_bnd',
                u'RT_lowerPinch_midCrease_bnd',
                u'RT_lowerSneer_cheek_bnd',
                u'RT_lowerPinch_outCrease_bnd',
                u'RT_outerB_cheekD_bnd',
                u'RT_upperSide_midCrease_bnd',
                u'RT_upperSide_outCrease_bnd',
                u'RT_upperSneer_inCrease_bnd',
                u'RT_upperSneer_midCrease_bnd',
                u'RT_upperSneer_outCrease_bnd',
                u'RT_upperPinch_midCrease_bnd',
                u'RT_lowerSneer_inCrease_bnd',
                u'RT_lowerSneer_midCrease_bnd',
                u'RT_upperCorner_lip_bnd',
                u'RT_lowerCorner_lip_bnd',
                u'RT_upperCorner_inCrease_bnd',
                u'RT_upperCorner_midCrease_bnd',
                u'RT_upperCorner_outCrease_bnd',
                u'RT_corner_inCrease_bnd',
                u'RT_corner_midCrease_bnd',
                u'RT_lowerCorner_inCrease_bnd',
                u'RT_lowerCorner_midCrease_bnd',
                u'RT_mid_browA_bnd',
                u'RT_out_browA_bnd',
                u'RT_outerB_temple_bnd',
                u'RT_outerB_squint_bnd',
                u'RT_outerA_temple_bnd',
                u'RT_in_browA_bnd',
                u'RT_upper_eyeSocket_bnd',
                u'RT_upperInner_eyeSocket_bnd',
                u'RT_upperOuter_eyeSocket_bnd',
                u'RT_outer_eyeSocket_bnd',
                u'RT_inner_eyeSocket_bnd',
                u'RT_outerA_squint_bnd',
                u'RT_side_forehead_bnd',
                u'RT_outerA_forehead_bnd',
                u'RT_outerB_forehead_bnd',
                u'RT_outerC_cheekB_bnd',
                u'RT_outerC_cheekA_bnd',
                u'RT_outerC_cheekC_bnd',
                u'RT_outerC_cheekD_bnd',
                u'RT_outerC_temple_bnd',
                u'RT_outerC_squint_bnd',
                u'RT_outerC_forehead_bnd']

# list of priCtls for first pass
# order is important
# those created earlier can be affected by those created later
# only need to specify LT and CT - RT is added in all_bnds_for_priCtls

bnds_for_priCtls = [u'LT_upperSneer_lip_pLoc',
                u'LT_lowerSneer_lip_pLoc',
                u'CT_lower_lip_pLoc',
                u'CT_upper_lip_pLoc']

all_bnds_for_priCtls = addRightSideToList(bnds_for_priCtls)

mainMouthPriCtlMappings = {u'CT__jaw_pri_ctrl': {u'CT__jaw_bnd': 0.75,
                       u'CT_lower_cheek_bnd': 0.01,
                       u'CT_lower_inCrease_bnd': 0.83,
                       u'CT_lower_lip_bnd': 1.0,
                       u'CT_lower_midCrease_bnd': 0.63,
                       u'CT_lower_outCrease_bnd': 0.35,
                       u'CT_upper_inCrease_bnd': 0.005,
                       u'CT_upper_lip_bnd': 0.005,
                       u'CT_upper_midCrease_bnd': 0.005,
                       u'CT_upper_outCrease_bnd': 0.005,
                       u'LT_corner_cheek_bnd': 0.41,
                       u'LT_corner_inCrease_bnd': 0.5,
                       u'LT_corner_lip_bnd': 0.5,
                       u'LT_corner_midCrease_bnd': 0.48,
                       u'LT_corner_outCrease_bnd': 0.44,
                       u'LT_lowerCorner_cheek_bnd': 0.41,
                       u'LT_lowerCorner_inCrease_bnd': 0.58,
                       u'LT_lowerCorner_lip_bnd': 0.55,
                       u'LT_lowerCorner_midCrease_bnd': 0.59,
                       u'LT_lowerCorner_outCrease_bnd': 0.55,
                       u'LT_lowerPinch_cheek_bnd': 0.2,
                       u'LT_lowerPinch_inCrease_bnd': 0.69,
                       u'LT_lowerPinch_lip_bnd': 0.675,
                       u'LT_lowerPinch_midCrease_bnd': 0.64,
                       u'LT_lowerPinch_outCrease_bnd': 0.48,
                       u'LT_lowerSide_cheek_bnd': 0.01,
                       u'LT_lowerSide_inCrease_bnd': 0.81,
                       u'LT_lowerSide_lip_bnd': 0.96,
                       u'LT_lowerSide_midCrease_bnd': 0.62,
                       u'LT_lowerSide_outCrease_bnd': 0.35,
                       u'LT_lowerSneer_cheek_bnd': 0.01,
                       u'LT_lowerSneer_inCrease_bnd': 0.77,
                       u'LT_lowerSneer_lip_bnd': 0.83,
                       u'LT_lowerSneer_midCrease_bnd': 0.62,
                       u'LT_lowerSneer_outCrease_bnd': 0.36,
                       u'LT_outerB_cheekA_bnd': 0.09,
                       u'LT_outerB_cheekB_bnd': 0.13,
                       u'LT_outerB_cheekC_bnd': 0.12,
                       u'LT_outerB_cheekD_bnd': 0.04,
                       u'LT_outerC_cheekA_bnd': 0.04,
                       u'LT_outerC_cheekB_bnd': 0.05,
                       u'LT_outerC_cheekC_bnd': 0.04,
                       u'LT_outerC_cheekD_bnd': 0.03,
                       u'LT_upperCorner_cheek_bnd': 0.25,
                       u'LT_upperCorner_inCrease_bnd': 0.41,
                       u'LT_upperCorner_lip_bnd': 0.45,
                       u'LT_upperCorner_midCrease_bnd': 0.35,
                       u'LT_upperCorner_outCrease_bnd': 0.3,
                       u'LT_upperPinch_inCrease_bnd': 0.31,
                       u'LT_upperPinch_lip_bnd': 0.325,
                       u'LT_upperPinch_midCrease_bnd': 0.26,
                       u'LT_upperPinch_outCrease_bnd': 0.15,
                       u'LT_upperSide_inCrease_bnd': 0.04,
                       u'LT_upperSide_lip_bnd': 0.04,
                       u'LT_upperSide_midCrease_bnd': 0.02,
                       u'LT_upperSide_outCrease_bnd': 0.02,
                       u'LT_upperSneer_inCrease_bnd': 0.15,
                       u'LT_upperSneer_lip_bnd': 0.17,
                       u'LT_upperSneer_midCrease_bnd': 0.09,
                       u'LT_upperSneer_outCrease_bnd': 0.03,
                       u'RT_corner_cheek_bnd': 0.41,
                       u'RT_corner_inCrease_bnd': 0.5,
                       u'RT_corner_lip_bnd': 0.5,
                       u'RT_corner_midCrease_bnd': 0.48,
                       u'RT_corner_outCrease_bnd': 0.44,
                       u'RT_lowerCorner_cheek_bnd': 0.41,
                       u'RT_lowerCorner_inCrease_bnd': 0.58,
                       u'RT_lowerCorner_lip_bnd': 0.55,
                       u'RT_lowerCorner_midCrease_bnd': 0.59,
                       u'RT_lowerCorner_outCrease_bnd': 0.55,
                       u'RT_lowerPinch_cheek_bnd': 0.2,
                       u'RT_lowerPinch_inCrease_bnd': 0.69,
                       u'RT_lowerPinch_lip_bnd': 0.675,
                       u'RT_lowerPinch_midCrease_bnd': 0.64,
                       u'RT_lowerPinch_outCrease_bnd': 0.48,
                       u'RT_lowerSide_cheek_bnd': 0.01,
                       u'RT_lowerSide_inCrease_bnd': 0.81,
                       u'RT_lowerSide_lip_bnd': 0.96,
                       u'RT_lowerSide_midCrease_bnd': 0.62,
                       u'RT_lowerSide_outCrease_bnd': 0.35,
                       u'RT_lowerSneer_cheek_bnd': 0.01,
                       u'RT_lowerSneer_inCrease_bnd': 0.77,
                       u'RT_lowerSneer_lip_bnd': 0.83,
                       u'RT_lowerSneer_midCrease_bnd': 0.62,
                       u'RT_lowerSneer_outCrease_bnd': 0.36,
                       u'RT_outerB_cheekA_bnd': 0.09,
                       u'RT_outerB_cheekB_bnd': 0.13,
                       u'RT_outerB_cheekC_bnd': 0.12,
                       u'RT_outerB_cheekD_bnd': 0.04,
                       u'RT_outerC_cheekA_bnd': 0.04,
                       u'RT_outerC_cheekB_bnd': 0.05,
                       u'RT_outerC_cheekC_bnd': 0.04,
                       u'RT_outerC_cheekD_bnd': 0.03,
                       u'RT_upperCorner_cheek_bnd': 0.25,
                       u'RT_upperCorner_inCrease_bnd': 0.41,
                       u'RT_upperCorner_lip_bnd': 0.45,
                       u'RT_upperCorner_midCrease_bnd': 0.35,
                       u'RT_upperCorner_outCrease_bnd': 0.3,
                       u'RT_upperPinch_inCrease_bnd': 0.31,
                       u'RT_upperPinch_lip_bnd': 0.325,
                       u'RT_upperPinch_midCrease_bnd': 0.26,
                       u'RT_upperPinch_outCrease_bnd': 0.15,
                       u'RT_upperSide_inCrease_bnd': 0.04,
                       u'RT_upperSide_lip_bnd': 0.04,
                       u'RT_upperSide_midCrease_bnd': 0.02,
                       u'RT_upperSide_outCrease_bnd': 0.02,
                       u'RT_upperSneer_inCrease_bnd': 0.15,
                       u'RT_upperSneer_lip_bnd': 0.17,
                       u'RT_upperSneer_midCrease_bnd': 0.09,
                       u'RT_upperSneer_outCrease_bnd': 0.03},
 u'CT__mouthMover_pri_ctrl': {u'CT__mouthMover_bnd': 1.0,
                              u'CT_lower_cheek_bnd': 0.02,
                              u'CT_lower_inCrease_bnd': 0.9,
                              u'CT_lower_lip_bnd': 1.0,
                              u'CT_lower_midCrease_bnd': 0.71,
                              u'CT_lower_outCrease_bnd': 0.4,
                              u'CT_upper_cheek_bnd': 0.025,
                              u'CT_upper_inCrease_bnd': 0.8,
                              u'CT_upper_lip_bnd': 1.0,
                              u'CT_upper_midCrease_bnd': 0.59,
                              u'CT_upper_outCrease_bnd': 0.31,
                              u'LT_corner_cheek_bnd': 0.74,
                              u'LT_corner_inCrease_bnd': 1.0,
                              u'LT_corner_lip_bnd': 1.0,
                              u'LT_corner_midCrease_bnd': 0.95,
                              u'LT_corner_outCrease_bnd': 0.85,
                              u'LT_lowerCorner_cheek_bnd': 0.59,
                              u'LT_lowerCorner_inCrease_bnd': 1.0,
                              u'LT_lowerCorner_lip_bnd': 1.0,
                              u'LT_lowerCorner_midCrease_bnd': 0.94,
                              u'LT_lowerCorner_outCrease_bnd': 0.82,
                              u'LT_lowerInner_eyeSocket_bnd': 0.025,
                              u'LT_lowerOuter_eyeSocket_bnd': 0.025,
                              u'LT_lowerPinch_cheek_bnd': 0.22,
                              u'LT_lowerPinch_inCrease_bnd': 0.95,
                              u'LT_lowerPinch_lip_bnd': 1.0,
                              u'LT_lowerPinch_midCrease_bnd': 0.83,
                              u'LT_lowerPinch_outCrease_bnd': 0.58,
                              u'LT_lowerSide_cheek_bnd': 0.02,
                              u'LT_lowerSide_inCrease_bnd': 0.9,
                              u'LT_lowerSide_lip_bnd': 1.0,
                              u'LT_lowerSide_midCrease_bnd': 0.71,
                              u'LT_lowerSide_outCrease_bnd': 0.4,
                              u'LT_lowerSneer_cheek_bnd': 0.02,
                              u'LT_lowerSneer_inCrease_bnd': 0.9,
                              u'LT_lowerSneer_lip_bnd': 1.0,
                              u'LT_lowerSneer_midCrease_bnd': 0.74,
                              u'LT_lowerSneer_outCrease_bnd': 0.44,
                              u'LT_lower_eyeSocket_bnd': 0.025,
                              u'LT_outerB_cheekA_bnd': 0.2,
                              u'LT_outerB_cheekB_bnd': 0.25,
                              u'LT_outerB_cheekC_bnd': 0.21,
                              u'LT_outerB_cheekD_bnd': 0.04,
                              u'LT_outerC_cheekA_bnd': 0.07,
                              u'LT_outerC_cheekB_bnd': 0.1,
                              u'LT_outerC_cheekC_bnd': 0.08,
                              u'LT_outerC_cheekD_bnd': 0.03,
                              u'LT_upperCorner_cheek_bnd': 0.54,
                              u'LT_upperCorner_inCrease_bnd': 1.0,
                              u'LT_upperCorner_lip_bnd': 1.0,
                              u'LT_upperCorner_midCrease_bnd': 0.93,
                              u'LT_upperCorner_outCrease_bnd': 0.83,
                              u'LT_upperPinch_inCrease_bnd': 0.88,
                              u'LT_upperPinch_lip_bnd': 1.0,
                              u'LT_upperPinch_midCrease_bnd': 0.71,
                              u'LT_upperPinch_outCrease_bnd': 0.46,
                              u'LT_upperSide_inCrease_bnd': 0.8,
                              u'LT_upperSide_lip_bnd': 1.0,
                              u'LT_upperSide_midCrease_bnd': 0.6,
                              u'LT_upperSide_outCrease_bnd': 0.32,
                              u'LT_upperSneer_inCrease_bnd': 0.82,
                              u'LT_upperSneer_lip_bnd': 1.0,
                              u'LT_upperSneer_midCrease_bnd': 0.63,
                              u'LT_upperSneer_outCrease_bnd': 0.32,
                              u'RT_corner_cheek_bnd': 0.74,
                              u'RT_corner_inCrease_bnd': 1.0,
                              u'RT_corner_lip_bnd': 1.0,
                              u'RT_corner_midCrease_bnd': 0.95,
                              u'RT_corner_outCrease_bnd': 0.85,
                              u'RT_lowerCorner_cheek_bnd': 0.59,
                              u'RT_lowerCorner_inCrease_bnd': 1.0,
                              u'RT_lowerCorner_lip_bnd': 1.0,
                              u'RT_lowerCorner_midCrease_bnd': 0.94,
                              u'RT_lowerCorner_outCrease_bnd': 0.82,
                              u'RT_lowerInner_eyeSocket_bnd': 0.025,
                              u'RT_lowerOuter_eyeSocket_bnd': 0.025,
                              u'RT_lowerPinch_cheek_bnd': 0.22,
                              u'RT_lowerPinch_inCrease_bnd': 0.95,
                              u'RT_lowerPinch_lip_bnd': 1.0,
                              u'RT_lowerPinch_midCrease_bnd': 0.83,
                              u'RT_lowerPinch_outCrease_bnd': 0.58,
                              u'RT_lowerSide_cheek_bnd': 0.02,
                              u'RT_lowerSide_inCrease_bnd': 0.9,
                              u'RT_lowerSide_lip_bnd': 1.0,
                              u'RT_lowerSide_midCrease_bnd': 0.71,
                              u'RT_lowerSide_outCrease_bnd': 0.4,
                              u'RT_lowerSneer_cheek_bnd': 0.02,
                              u'RT_lowerSneer_inCrease_bnd': 0.9,
                              u'RT_lowerSneer_lip_bnd': 1.0,
                              u'RT_lowerSneer_midCrease_bnd': 0.74,
                              u'RT_lowerSneer_outCrease_bnd': 0.44,
                              u'RT_lower_eyeSocket_bnd': 0.025,
                              u'RT_outerB_cheekA_bnd': 0.2,
                              u'RT_outerB_cheekB_bnd': 0.25,
                              u'RT_outerB_cheekC_bnd': 0.21,
                              u'RT_outerB_cheekD_bnd': 0.04,
                              u'RT_outerC_cheekA_bnd': 0.07,
                              u'RT_outerC_cheekB_bnd': 0.1,
                              u'RT_outerC_cheekC_bnd': 0.08,
                              u'RT_outerC_cheekD_bnd': 0.03,
                              u'RT_upperCorner_cheek_bnd': 0.54,
                              u'RT_upperCorner_inCrease_bnd': 1.0,
                              u'RT_upperCorner_lip_bnd': 1.0,
                              u'RT_upperCorner_midCrease_bnd': 0.93,
                              u'RT_upperCorner_outCrease_bnd': 0.83,
                              u'RT_upperPinch_inCrease_bnd': 0.88,
                              u'RT_upperPinch_lip_bnd': 1.0,
                              u'RT_upperPinch_midCrease_bnd': 0.71,
                              u'RT_upperPinch_outCrease_bnd': 0.46,
                              u'RT_upperSide_inCrease_bnd': 0.8,
                              u'RT_upperSide_lip_bnd': 1.0,
                              u'RT_upperSide_midCrease_bnd': 0.6,
                              u'RT_upperSide_outCrease_bnd': 0.32,
                              u'RT_upperSneer_inCrease_bnd': 0.82,
                              u'RT_upperSneer_lip_bnd': 1.0,
                              u'RT_upperSneer_midCrease_bnd': 0.63,
                              u'RT_upperSneer_outCrease_bnd': 0.32},
 u'LT_corner_lip_pri_ctrl': {u'CT_lower_inCrease_bnd': 0.1,
                             u'CT_lower_lip_bnd': 0.1,
                             u'CT_lower_midCrease_bnd': 0.1,
                             u'CT_lower_outCrease_bnd': 0.05,
                             u'CT_upper_inCrease_bnd': 0.08,
                             u'CT_upper_lip_bnd': 0.1,
                             u'CT_upper_midCrease_bnd': 0.05,
                             u'CT_upper_outCrease_bnd': 0.02,
                             u'LT_corner_cheek_bnd': 0.56,
                             u'LT_corner_inCrease_bnd': 1.0,
                             u'LT_corner_lip_bnd': 1.0,
                             u'LT_corner_midCrease_bnd': 0.93,
                             u'LT_corner_outCrease_bnd': 0.79,
                             u'LT_lowerCorner_cheek_bnd': 0.47,
                             u'LT_lowerCorner_inCrease_bnd': 0.96,
                             u'LT_lowerCorner_lip_bnd': 1.0,
                             u'LT_lowerCorner_midCrease_bnd': 0.86,
                             u'LT_lowerCorner_outCrease_bnd': 0.73,
                             u'LT_lowerPinch_cheek_bnd': 0.24,
                             u'LT_lowerPinch_inCrease_bnd': 0.7,
                             u'LT_lowerPinch_lip_bnd': 0.75,
                             u'LT_lowerPinch_midCrease_bnd': 0.65,
                             u'LT_lowerPinch_outCrease_bnd': 0.57,
                             u'LT_lowerSide_inCrease_bnd': 0.25,
                             u'LT_lowerSide_lip_bnd': 0.25,
                             u'LT_lowerSide_midCrease_bnd': 0.23,
                             u'LT_lowerSide_outCrease_bnd': 0.15,
                             u'LT_lowerSneer_inCrease_bnd': 0.5,
                             u'LT_lowerSneer_lip_bnd': 0.5,
                             u'LT_lowerSneer_midCrease_bnd': 0.43,
                             u'LT_lowerSneer_outCrease_bnd': 0.29,
                             u'LT_outerB_cheekA_bnd': 0.14,
                             u'LT_outerB_cheekB_bnd': 0.19,
                             u'LT_outerB_cheekC_bnd': 0.15,
                             u'LT_outerB_cheekD_bnd': 0.03,
                             u'LT_outerC_cheekA_bnd': 0.02,
                             u'LT_outerC_cheekB_bnd': 0.02,
                             u'LT_outerC_cheekC_bnd': 0.02,
                             u'LT_outerC_cheekD_bnd': 0.02,
                             u'LT_upperCorner_cheek_bnd': 0.43,
                             u'LT_upperCorner_inCrease_bnd': 0.96,
                             u'LT_upperCorner_lip_bnd': 1.0,
                             u'LT_upperCorner_midCrease_bnd': 0.85,
                             u'LT_upperCorner_outCrease_bnd': 0.65,
                             u'LT_upperPinch_inCrease_bnd': 0.72,
                             u'LT_upperPinch_lip_bnd': 0.75,
                             u'LT_upperPinch_midCrease_bnd': 0.57,
                             u'LT_upperPinch_outCrease_bnd': 0.33,
                             u'LT_upperSide_inCrease_bnd': 0.21,
                             u'LT_upperSide_lip_bnd': 0.25,
                             u'LT_upperSide_midCrease_bnd': 0.17,
                             u'LT_upperSide_outCrease_bnd': 0.09,
                             u'LT_upperSneer_inCrease_bnd': 0.42,
                             u'LT_upperSneer_lip_bnd': 0.5,
                             u'LT_upperSneer_midCrease_bnd': 0.31,
                             u'LT_upperSneer_outCrease_bnd': 0.16},
 u'RT_corner_lip_pri_ctrl': {u'CT_lower_inCrease_bnd': 0.1,
                             u'CT_lower_lip_bnd': 0.1,
                             u'CT_lower_midCrease_bnd': 0.1,
                             u'CT_lower_outCrease_bnd': 0.05,
                             u'CT_upper_inCrease_bnd': 0.08,
                             u'CT_upper_lip_bnd': 0.1,
                             u'CT_upper_midCrease_bnd': 0.05,
                             u'CT_upper_outCrease_bnd': 0.02,
                             u'RT_corner_cheek_bnd': 0.56,
                             u'RT_corner_inCrease_bnd': 1.0,
                             u'RT_corner_lip_bnd': 1.0,
                             u'RT_corner_midCrease_bnd': 0.93,
                             u'RT_corner_outCrease_bnd': 0.79,
                             u'RT_lowerCorner_cheek_bnd': 0.47,
                             u'RT_lowerCorner_inCrease_bnd': 0.96,
                             u'RT_lowerCorner_lip_bnd': 1.0,
                             u'RT_lowerCorner_midCrease_bnd': 0.86,
                             u'RT_lowerCorner_outCrease_bnd': 0.73,
                             u'RT_lowerPinch_cheek_bnd': 0.24,
                             u'RT_lowerPinch_inCrease_bnd': 0.7,
                             u'RT_lowerPinch_lip_bnd': 0.75,
                             u'RT_lowerPinch_midCrease_bnd': 0.65,
                             u'RT_lowerPinch_outCrease_bnd': 0.57,
                             u'RT_lowerSide_inCrease_bnd': 0.25,
                             u'RT_lowerSide_lip_bnd': 0.25,
                             u'RT_lowerSide_midCrease_bnd': 0.23,
                             u'RT_lowerSide_outCrease_bnd': 0.15,
                             u'RT_lowerSneer_inCrease_bnd': 0.5,
                             u'RT_lowerSneer_lip_bnd': 0.5,
                             u'RT_lowerSneer_midCrease_bnd': 0.43,
                             u'RT_lowerSneer_outCrease_bnd': 0.29,
                             u'RT_outerB_cheekA_bnd': 0.14,
                             u'RT_outerB_cheekB_bnd': 0.19,
                             u'RT_outerB_cheekC_bnd': 0.15,
                             u'RT_outerB_cheekD_bnd': 0.03,
                             u'RT_outerC_cheekA_bnd': 0.02,
                             u'RT_outerC_cheekB_bnd': 0.02,
                             u'RT_outerC_cheekC_bnd': 0.02,
                             u'RT_outerC_cheekD_bnd': 0.02,
                             u'RT_upperCorner_cheek_bnd': 0.43,
                             u'RT_upperCorner_inCrease_bnd': 0.96,
                             u'RT_upperCorner_lip_bnd': 1.0,
                             u'RT_upperCorner_midCrease_bnd': 0.85,
                             u'RT_upperCorner_outCrease_bnd': 0.65,
                             u'RT_upperPinch_inCrease_bnd': 0.72,
                             u'RT_upperPinch_lip_bnd': 0.75,
                             u'RT_upperPinch_midCrease_bnd': 0.57,
                             u'RT_upperPinch_outCrease_bnd': 0.33,
                             u'RT_upperSide_inCrease_bnd': 0.21,
                             u'RT_upperSide_lip_bnd': 0.25,
                             u'RT_upperSide_midCrease_bnd': 0.17,
                             u'RT_upperSide_outCrease_bnd': 0.09,
                             u'RT_upperSneer_inCrease_bnd': 0.42,
                             u'RT_upperSneer_lip_bnd': 0.5,
                             u'RT_upperSneer_midCrease_bnd': 0.31,
                             u'RT_upperSneer_outCrease_bnd': 0.16}}

mouthPriCtlMappings = {u'CT_lower_lip_pri_ctrl': {u'CT_lower_inCrease_bnd': 0.83,
                            u'CT_lower_lip_bnd': 1.0,
                            u'CT_lower_midCrease_bnd': 0.62,
                            u'CT_lower_outCrease_bnd': 0.34,
                            u'LT_lowerCorner_cheek_bnd': 0.08,
                            u'LT_lowerCorner_inCrease_bnd': 0.19,
                            u'LT_lowerCorner_lip_bnd': 0.2,
                            u'LT_lowerCorner_midCrease_bnd': 0.19,
                            u'LT_lowerCorner_outCrease_bnd': 0.13,
                            u'LT_lowerPinch_cheek_bnd': 0.1,
                            u'LT_lowerPinch_inCrease_bnd': 0.48,
                            u'LT_lowerPinch_lip_bnd': 0.49,
                            u'LT_lowerPinch_midCrease_bnd': 0.38,
                            u'LT_lowerPinch_outCrease_bnd': 0.36,
                            u'LT_lowerSide_inCrease_bnd': 0.81,
                            u'LT_lowerSide_lip_bnd': 0.96,
                            u'LT_lowerSide_midCrease_bnd': 0.6,
                            u'LT_lowerSide_outCrease_bnd': 0.33,
                            u'LT_lowerSneer_inCrease_bnd': 0.68,
                            u'LT_lowerSneer_lip_bnd': 0.78,
                            u'LT_lowerSneer_midCrease_bnd': 0.54,
                            u'LT_lowerSneer_outCrease_bnd': 0.33,
                            u'RT_lowerCorner_cheek_bnd': 0.08,
                            u'RT_lowerCorner_inCrease_bnd': 0.19,
                            u'RT_lowerCorner_lip_bnd': 0.2,
                            u'RT_lowerCorner_midCrease_bnd': 0.19,
                            u'RT_lowerCorner_outCrease_bnd': 0.13,
                            u'RT_lowerPinch_cheek_bnd': 0.1,
                            u'RT_lowerPinch_inCrease_bnd': 0.48,
                            u'RT_lowerPinch_lip_bnd': 0.49,
                            u'RT_lowerPinch_midCrease_bnd': 0.38,
                            u'RT_lowerPinch_outCrease_bnd': 0.36,
                            u'RT_lowerSide_inCrease_bnd': 0.81,
                            u'RT_lowerSide_lip_bnd': 0.96,
                            u'RT_lowerSide_midCrease_bnd': 0.6,
                            u'RT_lowerSide_outCrease_bnd': 0.33,
                            u'RT_lowerSneer_inCrease_bnd': 0.68,
                            u'RT_lowerSneer_lip_bnd': 0.78,
                            u'RT_lowerSneer_midCrease_bnd': 0.54,
                            u'RT_lowerSneer_outCrease_bnd': 0.33},
 u'CT_upper_lip_pri_ctrl': {u'CT_upper_cheek_bnd': 0.02,
                            u'CT_upper_inCrease_bnd': 0.77,
                            u'CT_upper_lip_bnd': 1.0,
                            u'CT_upper_midCrease_bnd': 0.54,
                            u'CT_upper_outCrease_bnd': 0.29,
                            u'LT_lowerInner_eyeSocket_bnd': 0.05,
                            u'LT_lower_eyeSocket_bnd': 0.05,
                            u'LT_upperCorner_inCrease_bnd': 0.19,
                            u'LT_upperCorner_lip_bnd': 0.2,
                            u'LT_upperCorner_midCrease_bnd': 0.2,
                            u'LT_upperCorner_outCrease_bnd': 0.13,
                            u'LT_upperPinch_inCrease_bnd': 0.39,
                            u'LT_upperPinch_lip_bnd': 0.49,
                            u'LT_upperPinch_midCrease_bnd': 0.26,
                            u'LT_upperPinch_outCrease_bnd': 0.15,
                            u'LT_upperSide_inCrease_bnd': 0.75,
                            u'LT_upperSide_lip_bnd': 0.96,
                            u'LT_upperSide_midCrease_bnd': 0.55,
                            u'LT_upperSide_outCrease_bnd': 0.32,
                            u'LT_upperSneer_inCrease_bnd': 0.6,
                            u'LT_upperSneer_lip_bnd': 0.78,
                            u'LT_upperSneer_midCrease_bnd': 0.43,
                            u'LT_upperSneer_outCrease_bnd': 0.24,
                            u'RT_lowerInner_eyeSocket_bnd': 0.05,
                            u'RT_lower_eyeSocket_bnd': 0.05,
                            u'RT_upperCorner_inCrease_bnd': 0.19,
                            u'RT_upperCorner_lip_bnd': 0.2,
                            u'RT_upperCorner_midCrease_bnd': 0.2,
                            u'RT_upperCorner_outCrease_bnd': 0.13,
                            u'RT_upperPinch_inCrease_bnd': 0.39,
                            u'RT_upperPinch_lip_bnd': 0.49,
                            u'RT_upperPinch_midCrease_bnd': 0.26,
                            u'RT_upperPinch_outCrease_bnd': 0.15,
                            u'RT_upperSide_inCrease_bnd': 0.75,
                            u'RT_upperSide_lip_bnd': 0.96,
                            u'RT_upperSide_midCrease_bnd': 0.55,
                            u'RT_upperSide_outCrease_bnd': 0.32,
                            u'RT_upperSneer_inCrease_bnd': 0.6,
                            u'RT_upperSneer_lip_bnd': 0.78,
                            u'RT_upperSneer_midCrease_bnd': 0.43,
                            u'RT_upperSneer_outCrease_bnd': 0.24},
 u'LT_lowerSneer_lip_pri_ctrl': {u'CT_lower_inCrease_bnd': 0.415,
                                 u'CT_lower_lip_bnd': 0.5,
                                 u'CT_lower_midCrease_bnd': 0.31,
                                 u'CT_lower_outCrease_bnd': 0.17,
                                 u'LT_lowerCorner_cheek_bnd': 0.08,
                                 u'LT_lowerCorner_inCrease_bnd': 0.19,
                                 u'LT_lowerCorner_lip_bnd': 0.2,
                                 u'LT_lowerCorner_midCrease_bnd': 0.19,
                                 u'LT_lowerCorner_outCrease_bnd': 0.13,
                                 u'LT_lowerPinch_cheek_bnd': 0.1,
                                 u'LT_lowerPinch_inCrease_bnd': 0.48,
                                 u'LT_lowerPinch_lip_bnd': 0.49,
                                 u'LT_lowerPinch_midCrease_bnd': 0.38,
                                 u'LT_lowerPinch_outCrease_bnd': 0.36,
                                 u'LT_lowerSide_inCrease_bnd': 0.648,
                                 u'LT_lowerSide_lip_bnd': 0.768,
                                 u'LT_lowerSide_midCrease_bnd': 0.48,
                                 u'LT_lowerSide_outCrease_bnd': 0.264,
                                 u'LT_lowerSneer_inCrease_bnd': 0.68,
                                 u'LT_lowerSneer_lip_bnd': 0.78,
                                 u'LT_lowerSneer_midCrease_bnd': 0.54,
                                 u'LT_lowerSneer_outCrease_bnd': 0.33,
                                 u'RT_lowerSide_inCrease_bnd': 0.162,
                                 u'RT_lowerSide_lip_bnd': 0.192,
                                 u'RT_lowerSide_midCrease_bnd': 0.12,
                                 u'RT_lowerSide_outCrease_bnd': 0.066},
 u'LT_upperSneer_lip_pri_ctrl': {u'CT_upper_cheek_bnd': 0.01,
                                 u'CT_upper_inCrease_bnd': 0.385,
                                 u'CT_upper_lip_bnd': 0.5,
                                 u'CT_upper_midCrease_bnd': 0.27,
                                 u'CT_upper_outCrease_bnd': 0.145,
                                 u'LT_lowerInner_eyeSocket_bnd': 0.04,
                                 u'LT_lower_eyeSocket_bnd': 0.05,
                                 u'LT_upperCorner_inCrease_bnd': 0.19,
                                 u'LT_upperCorner_lip_bnd': 0.2,
                                 u'LT_upperCorner_midCrease_bnd': 0.2,
                                 u'LT_upperCorner_outCrease_bnd': 0.13,
                                 u'LT_upperPinch_inCrease_bnd': 0.39,
                                 u'LT_upperPinch_lip_bnd': 0.49,
                                 u'LT_upperPinch_midCrease_bnd': 0.26,
                                 u'LT_upperPinch_outCrease_bnd': 0.15,
                                 u'LT_upperSide_inCrease_bnd': 0.6,
                                 u'LT_upperSide_lip_bnd': 0.768,
                                 u'LT_upperSide_midCrease_bnd': 0.44,
                                 u'LT_upperSide_outCrease_bnd': 0.256,
                                 u'LT_upperSneer_inCrease_bnd': 0.6,
                                 u'LT_upperSneer_lip_bnd': 0.78,
                                 u'LT_upperSneer_midCrease_bnd': 0.43,
                                 u'LT_upperSneer_outCrease_bnd': 0.24,
                                 u'RT_lowerInner_eyeSocket_bnd': 0.01,
                                 u'RT_upperSide_inCrease_bnd': 0.15,
                                 u'RT_upperSide_lip_bnd': 0.192,
                                 u'RT_upperSide_midCrease_bnd': 0.11,
                                 u'RT_upperSide_outCrease_bnd': 0.064},
 u'RT_lowerSneer_lip_pri_ctrl': {u'CT_lower_inCrease_bnd': 0.415,
                                 u'CT_lower_lip_bnd': 0.5,
                                 u'CT_lower_midCrease_bnd': 0.31,
                                 u'CT_lower_outCrease_bnd': 0.17,
                                 u'LT_lowerSide_inCrease_bnd': 0.162,
                                 u'LT_lowerSide_lip_bnd': 0.192,
                                 u'LT_lowerSide_midCrease_bnd': 0.12,
                                 u'LT_lowerSide_outCrease_bnd': 0.066,
                                 u'RT_lowerCorner_cheek_bnd': 0.08,
                                 u'RT_lowerCorner_inCrease_bnd': 0.19,
                                 u'RT_lowerCorner_lip_bnd': 0.2,
                                 u'RT_lowerCorner_midCrease_bnd': 0.19,
                                 u'RT_lowerCorner_outCrease_bnd': 0.13,
                                 u'RT_lowerPinch_cheek_bnd': 0.1,
                                 u'RT_lowerPinch_inCrease_bnd': 0.48,
                                 u'RT_lowerPinch_lip_bnd': 0.49,
                                 u'RT_lowerPinch_midCrease_bnd': 0.38,
                                 u'RT_lowerPinch_outCrease_bnd': 0.36,
                                 u'RT_lowerSide_inCrease_bnd': 0.648,
                                 u'RT_lowerSide_lip_bnd': 0.768,
                                 u'RT_lowerSide_midCrease_bnd': 0.48,
                                 u'RT_lowerSide_outCrease_bnd': 0.264,
                                 u'RT_lowerSneer_inCrease_bnd': 0.68,
                                 u'RT_lowerSneer_lip_bnd': 0.78,
                                 u'RT_lowerSneer_midCrease_bnd': 0.54,
                                 u'RT_lowerSneer_outCrease_bnd': 0.33},
 u'RT_upperSneer_lip_pri_ctrl': {u'CT_upper_cheek_bnd': 0.01,
                                 u'CT_upper_inCrease_bnd': 0.385,
                                 u'CT_upper_lip_bnd': 0.5,
                                 u'CT_upper_midCrease_bnd': 0.27,
                                 u'CT_upper_outCrease_bnd': 0.145,
                                 u'LT_lowerInner_eyeSocket_bnd': 0.01,
                                 u'LT_upperSide_inCrease_bnd': 0.15,
                                 u'LT_upperSide_lip_bnd': 0.192,
                                 u'LT_upperSide_midCrease_bnd': 0.11,
                                 u'LT_upperSide_outCrease_bnd': 0.064,
                                 u'RT_lowerInner_eyeSocket_bnd': 0.04,
                                 u'RT_lower_eyeSocket_bnd': 0.05,
                                 u'RT_upperCorner_inCrease_bnd': 0.19,
                                 u'RT_upperCorner_lip_bnd': 0.2,
                                 u'RT_upperCorner_midCrease_bnd': 0.2,
                                 u'RT_upperCorner_outCrease_bnd': 0.13,
                                 u'RT_upperPinch_inCrease_bnd': 0.39,
                                 u'RT_upperPinch_lip_bnd': 0.49,
                                 u'RT_upperPinch_midCrease_bnd': 0.26,
                                 u'RT_upperPinch_outCrease_bnd': 0.15,
                                 u'RT_upperSide_inCrease_bnd': 0.6,
                                 u'RT_upperSide_lip_bnd': 0.768,
                                 u'RT_upperSide_midCrease_bnd': 0.44,
                                 u'RT_upperSide_outCrease_bnd': 0.256,
                                 u'RT_upperSneer_inCrease_bnd': 0.6,
                                 u'RT_upperSneer_lip_bnd': 0.78,
                                 u'RT_upperSneer_midCrease_bnd': 0.43,
                                 u'RT_upperSneer_outCrease_bnd': 0.24}}

eyeAndBrowPriCtlMappings = {u'LT__browMover_pri_ctrl': {u'LT__browMover_bnd': 1,
                             u'LT_in_browA_bnd': 1,
                             u'LT_mid_browA_bnd': 1,
                             u'LT_out_browA_bnd': 1},
 u'LT_inner_eyelid_pri_ctrl': {u'LT_inner_eyelid_bnd': 1,
                               u'LT_lowerInner_eyelid_bnd': 1,
                               u'LT_upperInner_eyelid_bnd': 1},
 u'LT_lower_eyelid_pri_ctrl': {u'LT_inner_eyelid_bnd': 1,
                               u'LT_lowerInner_eyelid_bnd': 1,
                               u'LT_lowerOuter_eyelid_bnd': 1,
                               u'LT_lower_eyelid_bnd': 1,
                               u'LT_outer_eyelid_bnd': 1},
 u'LT_outer_eyelid_pri_ctrl': {u'LT_lowerOuter_eyelid_bnd': 1,
                               u'LT_outer_eyelid_bnd': 1,
                               u'LT_upperOuter_eyelid_bnd': 1},
 u'LT_upper_eyelid_pri_ctrl': {u'LT_inner_eyelid_bnd': 1,
                               u'LT_outer_eyelid_bnd': 1,
                               u'LT_upperInner_eyelid_bnd': 1,
                               u'LT_upperOuter_eyelid_bnd': 1,
                               u'LT_upper_eyelid_bnd': 1},
 u'RT__browMover_pri_ctrl': {u'RT__browMover_bnd': 1,
                             u'RT_in_browA_bnd': 1,
                             u'RT_mid_browA_bnd': 1,
                             u'RT_out_browA_bnd': 1},
 u'RT_inner_eyelid_pri_ctrl': {u'RT_inner_eyelid_bnd': 1,
                               u'RT_lowerInner_eyelid_bnd': 1,
                               u'RT_upperInner_eyelid_bnd': 1},
 u'RT_lower_eyelid_pri_ctrl': {u'RT_inner_eyelid_bnd': 1,
                               u'RT_lowerInner_eyelid_bnd': 1,
                               u'RT_lowerOuter_eyelid_bnd': 1,
                               u'RT_lower_eyelid_bnd': 1,
                               u'RT_outer_eyelid_bnd': 1},
 u'RT_outer_eyelid_pri_ctrl': {u'RT_lowerOuter_eyelid_bnd': 1,
                               u'RT_outer_eyelid_bnd': 1,
                               u'RT_upperOuter_eyelid_bnd': 1},
 u'RT_upper_eyelid_pri_ctrl': {u'RT_inner_eyelid_bnd': 1,
                               u'RT_outer_eyelid_bnd': 1,
                               u'RT_upperInner_eyelid_bnd': 1,
                               u'RT_upperOuter_eyelid_bnd': 1,
                               u'RT_upper_eyelid_bnd': 1}}

priCtlMappings = {}
priCtlMappings.update(eyeAndBrowPriCtlMappings)
priCtlMappings.update(mainMouthPriCtlMappings)
priCtlMappings.update(mouthPriCtlMappings)